### PR TITLE
Updating jar files and QM properties

### PR DESCRIPTION
**Pull request by anqyan**
To address the comment: https://github.com/jmstoolbox/jmstoolbox/pull/96#issuecomment-724347706 
- Breaking down the jar to individual minimal packages
- Changing return 0 to return null for getting queue depth
- Adding reconnect related properties

### CODE REVIEW

**Comment by titou10titou10** [comment]
Thanks for the PR
I wonder why you dont use the host/port defined in the session. Maybe you provide them in the connectionString. Maybe the connectionString should be build from those fields and a few other mandatory properties to be symmetrical with other plugins where host/port are provided in the session itself, and not in extra parameters
Q: what is the structure of the connectionString?
Also the class doesn't use the user/password fields. Where/how do you provide authentication?

**Comment by anqyan** [comment]
@titou10titou10 

To be short, Authentication is provided through the connection string. 

A connection string is in the format of `Endpoint=sb://<host name>/;SharedAccessKeyName=<key name>;SharedAccessKey=<key value>`. In JMS context, the Azure SAS key name is JMS username, SAS key is JMS password. More details on Service Bus authentication without any JMS level context: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-authentication-and-authorization  

Usually, a connection string is what a Service Bus customer can directly obtain without any parsing: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quickstart-portal#get-the-connection-string Hence I used it as a required property for the queue manager for authentication purpose, although I noticed host name, password, port, etc are also mandatory by design.

**Comment by anqyan** [comment]
@titou10titou10 Please let me know what else we need to do before merging `azure_sb` into `master`, thanks.

**Comment by titou10titou10** [comment]
In fact in JTB host/port are mandatory, not user/password
OK for the connection string. 
To be consistent with other plugins, it would be better to use the host/port+user/password fields and build the connection string from there
What I propose:
- make the connectionString property optionnal
- if the property is set in the session definition, use it and ask the user to set a fake host/port
- if not, build the connection string from the host/port/user/pwd fields
- document this behavior
WDYT?
If agreed, I will make the change and probably merge the branch before the end of this week
I have no way to test the plugin, I guess you tested it yourself

**Comment by titou10titou10** [comment]
If you want it, I can laso add your name in the "About" box, just give me what to write (name? )

**Comment by anqyan** [comment]
> If you want it, I can laso add your name in the "About" box, just give me what to write (name? )

Name is Anqi Yan. I don't have a preference on this tbh, this is your project, your call : )

**Pull request merged**
